name: Android Code Quality, Docs, Static Analysis

on: [push, pull_request]

jobs:
  quality-checks:
    name: Run Lint & Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions
        run: chmod +x ./gradlew

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Run Ktlint (if using)
        run: ./gradlew ktlintCheck

  generate-docs:
    name: Generate Documentation (Dokka)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Dokka HTML
        run: ./gradlew dokkaHtml

      - name: Upload Docs
        uses: actions/upload-artifact@v4
        with:
          name: dokka-docs
          path: build/dokka/html

  static-analysis:
    name: Run Static Analysis (Detekt)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Detekt
        run: ./gradlew detekt
